name: 'Display Conda Environment Details'
author: 'Curtis Mayberry'
description: 'Displays all the details of a conda environment'
inputs:
  prefix:
    description: 'Path to the root of the conda environment.  Defaults to "./envs/build"'
    required: false
    default: './envs/build'
runs:
  using: "composite"
  steps:
    - name: Publish locally
      run: >
        ${{ github.action_path }}/conda-env-details.sh
        ${{ inputs.prefix }}
      shell: bash
branding:
  icon: 'package'
  color: 'green'