name: Release

on:
  workflow_dispatch:
env:
  ENV_YAML: envs/build.yml
jobs:
  test_name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles(${{ env.ENV_YAML }}) }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build
          environment-file: ${{ env.ENV_YAML }}
      - uses: ./
        with:
          name: build
